### ISSUE TITLE
Identify Place with code or other property

### ISSUE THREAD

**Issue by anilmamede** [ist-dsi/standards#7]
To serialize districts or municipalities (with externalizers) it is necessary to identify unambiguously by code or other property.

**Comment by jcarvalho** [comment]
You are talking about the Java API, right? The information contained in for instance `districts.txt` already contains the code you want.

**Comment by anilmamede** [comment]
Yes. The code is declared in files but it is not possible to read the keys declared in Place as class property (getter).

**Comment by sergiofbsilva** [comment]
Imported to JIRA https://jira.fenixedu.org/browse/STD-1
